# Generated by Django 5.2.1 on 2025-06-01 11:00

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TEACHING', 'Teaching'), ('INFRASTRUCTURE', 'Infrastructure'), ('TRANSPORT', 'Transport'), ('EXTRACURRICULAR', 'Extracurricular Activities'), ('STAFF_BEHAVIOUR', 'Staff Behaviour'), ('CANTEEN', 'Canteen'), ('LIBRARY', 'Library')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating1', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating for question 1', null=True)),
                ('rating2', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating for question 2', null=True)),
                ('rating3', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating for question 3', null=True)),
                ('rating4', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating for question 4', null=True)),
                ('rating5', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating for question 5', null=True)),
                ('input_method', models.CharField(choices=[('TEXT', 'Text Input'), ('AUDIO', 'Audio Recording')], default='TEXT', max_length=10)),
                ('text_feedback', models.TextField(blank=True, help_text='Typed feedback or (future) transcribed audio.', null=True)),
                ('audio_feedback', models.FileField(blank=True, help_text='Uploaded/recorded audio file.', null=True, upload_to='feedback_audio/')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department_at_submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedbacks', to='core.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='core.feedbackcategory')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment_no', models.CharField(blank=True, help_text='Display/Record Enrollment No. (Mirrors login ID)', max_length=50, null=True, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20)),
                ('batch_start_year', models.IntegerField(blank=True, choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=core.models.profile_photo_path)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
