# Generated by Django 5.2.1 on 2025-07-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anonymity_revoked',
            field=models.BooleanField(default=False, help_text='If True, the student has chosen to reveal their identity for this anonymous feedback.'),
        ),
    ]
